### ISSUE TITLE
Deserialization to Twitter4j

### ISSUE THREAD

**Issue by aagnone3** [jcustenborder/kafka-connect-twitter#26]
I might be missing something obvious here. I see that you convert Twitter4j objects to `Struct` for topic publishing. I'm writing a simple streams app and want to use a JSON Serde class parametrized by Twitter4j's `Status` object so I can operate on that class's methods in the streams app's logic. Your README schemas imply that your library has data model objects `Status`, `User`, etc at `com.github.jcustenborder.kafka.connect.twitter.*` but that's not the case. Similarly, directly using `twitter4j.Status` etc does not work without re-creating the classes using annotations, since you converted the field names from camel case to title case.

Bottom-line question -- are there POJOs anywhere that I can use out of the box to deserialize the topic's messages directly into twitter4j-like classes for processing?

**Comment by jcustenborder** [comment]
@aagnone3 There are no POJOs already out here.  Structs are not necessarily POJOs. This connector creates schema and structs for the object types and hands it off to a converter to persist the data. You could try using a different converter. For example the Avro converter will give you a schema that could be used to generate immutable pojos.

**Comment by aagnone3** [comment]
Thanks for the quick response @jcustenborder I will check that out.
