### ISSUE TITLE
Build Failure unable to find javadoc

### ISSUE THREAD

**Issue by mkorbi** [jcustenborder/kafka-connect-twitter#8]
Hey,
I'm not sure if this applies to all. When running `mvn clean package` I get a 
![bildschirmfoto 2017-12-04 um 10 05 58](https://user-images.githubusercontent.com/16919345/33544358-c61e87b0-d8da-11e7-85ce-153c2b9674c9.png)
Howerver, JVM fits, variables fits, so it looks all good.

But I found in the /target/javadoc-bundle-options/javadoc-options-javadoc-resources.xml this line
`<javadocResourcesDirectory>src/main/javadoc</javadocResourcesDirectory>` which must be (as written in the documents) `<javadocDirectory>src/main/javadoc</javadocDirectory>`

This solved the problem. After running the clean package it inserts again the "javadocResourcesDirectroY" but rerun it cause same problem again.

Cheers

**Comment by jcustenborder** [comment]
If you set JAVA_HOME that error will most likely go away.
